Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -20,25 +20,19 @@ fatal() {
 RUBYSUFFIX=''
 
 command_exists() {
-
 	command -v "${1}" >/dev/null 2>&1
 }
 
 get_permission() {
-
 	warn 'This script will install BeEF and its required dependencies (including operating system packages).'
-
 	read -rp "Are you sure you wish to continue (Y/n)? "
 	if [ "$(echo "${REPLY}" | tr "[:upper:]" "[:lower:]")" = "n" ]; then
 		fatal 'Installation aborted'
 	fi
-
 }
 
 check_os() {
-
 	info "Detecting OS..."
-
 	OS=$(uname)
 	readonly OS
 	info "Operating System: $OS"
@@ -50,7 +44,7 @@ check_os() {
 		install_mac
 	elif [ "${OS}" = "FreeBSD" ]; then
 		info "Launching FreeBSD install..."
-		for SUFX in 32 31 30; do
+		for SUFX in 33 32 31; do
 			if command_exists ruby${SUFX}; then
 				RUBYSUFFIX=${SUFX}
 				break
@@ -59,7 +53,7 @@ check_os() {
 		install_freebsd
 	elif [ "${OS}" = "OpenBSD" ]; then
 		info "Launching OpenBSD install..."
-		for SUFX in 32 31 30; do
+		for SUFX in 33 32 31; do
 			if command_exists ruby${SUFX}; then
 				RUBYSUFFIX=${SUFX}
 				break
@@ -72,7 +66,6 @@ check_os() {
 }
 
 install_linux() {
-
 	info "Detecting Linux OS distribution..."
 
 	Distro=''
@@ -85,7 +78,6 @@ install_linux() {
 	elif [ -f /etc/alpine-release ]; then
 		Distro='Alpine'
 	elif [ -f /etc/os-release ]; then
-		#DISTRO_ID=$(grep ^ID= /etc/os-release | cut -d= -f2-)
 		DISTRO_ID=$(grep ID= /etc/os-release | grep -v "BUILD" | grep -v "IMAGE" | cut -d= -f2-)
 		if [ "${DISTRO_ID}" = 'kali' ]; then
 			Distro='Kali'
@@ -104,86 +96,60 @@ install_linux() {
 	info "Installing ${Distro} prerequisite packages..."
 	if [ "${Distro}" = "Debian" ] || [ "${Distro}" = "Kali" ]; then
 		sudo apt-get update
-		sudo apt-get install curl git build-essential openssl libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libncurses5-dev automake libtool bison nodejs libcurl4-openssl-dev
-		if command_exists rvm || command_exists rbenv; then
-			info "Ruby package Manager exists - Ruby install skipped"
-		else
-			info "No Ruby package manager detected - will install Ruby"
-			sudo apt-get install ruby-dev
-		fi
+		sudo apt-get install curl git build-essential openssl libreadline6-dev zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev autoconf libc6-dev libncurses5-dev automake libtool bison nodejs libcurl4-openssl-dev ruby3.3 ruby3.3-dev
 	elif [ "${Distro}" = "RedHat" ]; then
-		sudo yum install -y git make gcc openssl-devel gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel bzip2 autoconf automake libtool bison sqlite-devel nodejs
+		sudo yum install -y git make gcc openssl-devel gcc-c++ patch readline readline-devel zlib zlib-devel libyaml-devel libffi-devel bzip2 autoconf automake libtool bison sqlite-devel nodejs ruby
 	elif [ "${Distro}" = "SuSE" ]; then
 		IFS=$NORMIFS
 		intpkg=""
 		nodejsver=nodejs16
-
-		# having NodeJS 18 installed should mean NodeJS 16 is not needed
 		rpm --quiet -q nodejs18 && nodejsver=""
-
-		for i in git make gcc libopenssl-devel gcc-c++ patch libreadline6 readline6-devel libz1 zlib-devel libyaml-devel libffi-devel bzip2 autoconf automake libtool bison sqlite3-devel $nodejsver; do
+		for i in git make gcc libopenssl-devel gcc-c++ patch libreadline6 readline6-devel libz1 zlib-devel libyaml-devel libffi-devel bzip2 autoconf automake libtool bison sqlite3-devel $nodejsver ruby3.3; do
 			rpm --quiet -q "${i}" || intpkg="${intpkg} ${i}"
 		done
 		[ "$intpkg" ] && sudo zypper -n install -l "${intpkg}"
 		IFS=$SCRIFS
 	elif [ "${Distro}" = "blackPanther" ]; then
-		installing --auto git make gcc openssl-devel gcc-c++ patch readline-devel zlib-devel yaml-devel libffi-devel bzip2 autoconf automake libtool bison sqlite-devel nodejs sudo
+		installing --auto git make gcc openssl-devel gcc-c++ patch readline-devel zlib-devel yaml-devel libffi-devel bzip2 autoconf automake libtool bison sqlite-devel nodejs sudo ruby
 	elif [ "${Distro}" = "Arch" ]; then
 		sudo pacman -Syu
-		sudo pacman -S curl git make openssl gcc readline zlib libyaml sqlite bzip2 autoconf automake libtool bison nodejs
-		if command_exists rvm || command_exists rbenv; then
-			info "Ruby package Manager exists - Ruby install skipped"
-		else
-			info "No Ruby package manager detected - will install Ruby"
-			sudo pacman -S ruby ruby-rdoc
-		fi
+		sudo pacman -S curl git make openssl gcc readline zlib libyaml sqlite bzip2 autoconf automake libtool bison nodejs ruby
 	elif [ "${Distro}" = "Alpine" ]; then
 		apk update
-		apk add curl git build-base openssl readline-dev zlib zlib-dev libressl-dev yaml-dev sqlite-dev sqlite libxml2-dev libxslt-dev autoconf libc6-compat ncurses5 automake libtool bison nodejs
+		apk add curl git build-base openssl readline-dev zlib zlib-dev libressl-dev yaml-dev sqlite-dev sqlite libxml2-dev libxslt-dev autoconf libc6-compat ncurses5 automake libtool bison nodejs ruby
 	fi
 }
 
 install_openbsd() {
-
-	sudo pkg_add curl git libyaml libxml libxslt bison node ruby${RUBYSUFFIX}-bundler lame espeak
+	sudo pkg_add curl git libyaml libxml libxslt bison node ruby33-bundler lame espeak
 }
 
 install_freebsd() {
-
 	sudo pkg install curl git libyaml libxslt devel/ruby-gems bison node espeak
 }
 
 install_mac() {
-
 	local mac_deps=(curl git nodejs python3
 		openssl readline libyaml sqlite3 libxml2
 		autoconf ncurses automake libtool
-		bison wget)
-
+		bison wget ruby)
 	if ! command_exists brew; then
 		fatal "Homebrew (https://brew.sh/) required to install dependencies"
 	fi
-
 	info "Installing dependencies via brew"
-
 	brew update
-
 	for package in "${mac_deps[@]}"; do
-
 		if brew install "${package}"; then
 			info "${package} installed"
 		else
 			fatal "Failed to install ${package}"
 		fi
-
 	done
 }
 
 check_ruby_version() {
-
 	info 'Detecting Ruby environment...'
-
-	MIN_RUBY_VER='3.0'
+	MIN_RUBY_VER='3.3'
 	if command_exists rvm; then
 		RUBY_VERSION=$(rvm current | cut -d'-' -f 2)
 		info "Ruby version ${RUBY_VERSION} is installed with RVM"
@@ -207,76 +173,23 @@ check_ruby_version() {
 	fi
 }
 
-check_bundler() {
-
-	info 'Detecting bundler gem...'
-
-	if command_exists bundler${RUBYSUFFIX}; then
-		info "bundler${RUBYSUFFIX} gem is installed"
-	else
-		info 'Installing bundler gem...'
-		gem${RUBYSUFFIX} install bundler
-	fi
-}
-
 install_beef() {
-
-	echo "Installing required Ruby gems..."
-
-	if [ -w Gemfile.lock ]; then
-		/bin/rm Gemfile.lock
-	fi
-
-	if command_exists bundle${RUBYSUFFIX}; then
-		bundle${RUBYSUFFIX} install
+	if [ -d .git ]; then
+		git checkout -- .
+		git pull --recurse-submodules --rebase
 	else
-		bundle install
+		git clone --recurse-submodules https://github.com/beefproject/beef
+		cd beef || fatal "Failed to clone the BeEF repo."
 	fi
-}
-
-finish() {
-	echo
-	echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#"
-	echo
-	info "Install completed successfully!"
-	info "Run './beef' to launch BeEF"
-	echo
-	echo "Next steps:"
-	echo
-	echo "* Change the default password in config.yaml"
-	echo "* Configure geoipupdate to update the Maxmind GeoIP database:"
-	echo "*   https://dev.maxmind.com/geoip/updating-databases"
-	echo "* Review the wiki for important configuration information:"
-	echo "  https://github.com/beefproject/beef/wiki/Configuration"
-	echo
-	echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#"
-	echo
+	ruby${RUBYSUFFIX} -S gem install bundler
+	ruby${RUBYSUFFIX} -S bundle install
 }
 
 main() {
-
-	clear
-
-	if [ -f core/main/console/beef.ascii ]; then
-		cat core/main/console/beef.ascii
-		echo
-	fi
-
-	echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#"
-	echo "                   -- [ BeEF Installer ] --                      "
-	echo "#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#-#"
-	echo
-
-	if [ -n "${GITACTIONS:-}" ]; then
-		info "Skipping: Running on Github Actions"
-	else
-		get_permission
-	fi
 	check_os
 	check_ruby_version
-	check_bundler
+	get_permission
 	install_beef
-	finish
 }
 
-main "$@"
+main
